language: node_js
node_js:
  - lts/*
cache: npm
addons:
  chrome: stable
install: npm install
before_script:
  - npm install -g grunt
  - export NODE_OPTIONS=--max_old_space_size=2048


jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Lint"            # names the first Tests stage job
      script: grunt lint
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: grunt test
    - stage: "Tests"                # naming the Tests stage
      name: "Integration Tests"            # names the first Tests stage job
      script: grunt prod --msg="$COMPILE_MSG"
    - script: xvfb-run --server-args="-screen 0 1200x800x24" grunt testui


# script:
#   - grunt lint
#   - grunt test
#   - grunt docs
#   - grunt node
#   - grunt prod --msg="$COMPILE_MSG"
#   - xvfb-run --server-args="-screen 0 1200x800x24" grunt testui
before_deploy:
  - grunt exec:sitemap
  - grunt copy:ghPages
